[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false

[[redirects]]
  from = "http://beta.morag.click/*"
  to = "http://app.morag.click/*"
  status = 301
  force = true

[[redirects]]
  from = "https://beta.morag.click/*"
  to = "https://app.morag.click/*"
  status = 301
  force = true